version: '2'
services:
  ansible:
    build: .
    image: docker_ansible
    hostname: ansible
    volumes:
      - ../:/ansible:ro
  web01:
    image: docker_ansible
    hostname: web01
    depends_on:
      - ansible
  web02:
    image: docker_ansible
    hostname: web02
    depends_on:
      - ansible
  biz01:
    image: docker_ansible
    hostname: biz01
    depends_on:
      - ansible
  biz02:
    image: docker_ansible
    hostname: biz02
    depends_on:
      - ansible
  app01:
    image: docker_ansible
    hostname: app01
    depends_on:
      - ansible
  app02:
    image: docker_ansible
    hostname: app02
    depends_on:
      - ansible
